name: Expresso
version: 0.1
description: Expresso pour les build battle de Buildes Coffee.
author: Ketsu_sama
main: eu.builderscoffee.expresso.Main
depend: [ BuildersCoffeeAPI ]
commands:
  expresso:
    description: Gerer le build battle