name: Expresso
version: 0.1
description: Expresso pour les build battle de Buildes Coffee.
author: Ketsu_sama
main: eu.builderscoffee.expresso.Main
depend: [ BuildersCoffeeAPI ]
commands:
  game:
    description: Gérer le build battle
  jury:
    description: Le menu jury
  group:
    description: Gestion de groupe
  eplot:
    description: Plot custom