package eu.builderscoffee.expresso.utils;

import lombok.Data;
import lombok.Getter;

import java.util.Arrays;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.stream.Collectors;
import java.util.stream.Stream;

public enum BlockData {

    STONE(1, 0, BlockCategory.CONSTRUCT),
    GRANITE(1, 1, BlockCategory.CONSTRUCT),
    POLISHED_GRANITE(1, 2, BlockCategory.CONSTRUCT),
    DIORITE(1, 3, BlockCategory.CONSTRUCT),
    POLISHED_DIORITE(1, 4, BlockCategory.CONSTRUCT),
    ANDESITE(1, 5, BlockCategory.CONSTRUCT),
    POLISHED_ANDESITE(1, 6, BlockCategory.CONSTRUCT),
    GRASS(2, 0, BlockCategory.CONSTRUCT),
    DIRT(3, 0, BlockCategory.CONSTRUCT),
    COARSE_DIRT(3, 1, BlockCategory.CONSTRUCT),
    PODZOL(3, 2, BlockCategory.CONSTRUCT),
    COBBLE(4, 0, BlockCategory.CONSTRUCT),
    OAK_WOOD_PLANK(5, 0, BlockCategory.CONSTRUCT),
    SPRUCE_WOOD_PLANK(5, 1, BlockCategory.CONSTRUCT),
    BIRCH_WOOD_PLANK(5, 2, BlockCategory.CONSTRUCT),
    JUNGLE_WOOD_PLANK(5, 3, BlockCategory.CONSTRUCT),
    ACACIA_WOOD_PLANK(5, 4, BlockCategory.CONSTRUCT),
    DARK_OAK_WOOD_PLANK(5, 5, BlockCategory.CONSTRUCT),
    OAK_SAPLING(6, 0, BlockCategory.SAPLING),
    SPRUCE_SAPLING(6, 1, BlockCategory.SAPLING),
    BIRCH_SAPLING(6, 2, BlockCategory.SAPLING),
    JUNGLE_SAPLING(6, 3, BlockCategory.SAPLING),
    ACACIA_SAPLING(6, 4, BlockCategory.SAPLING),
    DARK_OAK_SAPLING(6, 5, BlockCategory.SAPLING),
    BEDROCK(7, 0, BlockCategory.CONSTRUCT),
    SAND(12, 0, BlockCategory.CONSTRUCT),
    RED_SAND(12, 1, BlockCategory.CONSTRUCT),
    GRAVEL(13, 0, BlockCategory.CONSTRUCT),
    GOLD_ORE(14, 0, BlockCategory.CONSTRUCT),
    IRON_ORE(15, 0, BlockCategory.CONSTRUCT),
    COAL_ORE(16, 0, BlockCategory.CONSTRUCT),
    OAK_WOOD(17, 0, BlockCategory.LOG),
    SPRUCE_WOOD(17, 1, BlockCategory.LOG),
    BIRCH_WOOD(17, 2, BlockCategory.LOG),
    JUNGLE_WOOD(17, 3, BlockCategory.LOG),
    OAK_LEAVES(18, 0, BlockCategory.CONSTRUCT),
    SPRUCE_LEAVES(18, 1, BlockCategory.CONSTRUCT),
    BIRCH_LEAVES(18, 2, BlockCategory.CONSTRUCT),
    JUNGLE_LEAVES(18, 2, BlockCategory.CONSTRUCT),
    SPONGE(19, 0, BlockCategory.CONSTRUCT),
    WET_SPONGE(19, 1, BlockCategory.CONSTRUCT),
    GLASS(20, 0, BlockCategory.CONSTRUCT),
    LAPIS_LAZULI_ORE(21, 0, BlockCategory.CONSTRUCT),
    LAPIS_LAZULI_BLOCK(22, 0, BlockCategory.CONSTRUCT),
    DISPENSER(23, 0, BlockCategory.MISCELLANEOUS),
    SANDSTONE(24, 0, BlockCategory.CONSTRUCT),
    CHISELED_SANDSTONE(24, 1, BlockCategory.CONSTRUCT),
    SMOOTH_SANDSTONE(24, 2, BlockCategory.CONSTRUCT),
    NOTE_BLOCK(25, 0, BlockCategory.CONSTRUCT),
    BED(26, 0, BlockCategory.CONSTRUCT),
    STICKY_PISTON(29, 0, BlockCategory.MISCELLANEOUS),
    COBWEB(30, 0, BlockCategory.PLANT),
    DEAD_SHRUB(31, 0, BlockCategory.PLANT),
    TALLGRASS(31, 1, BlockCategory.PLANT),
    FERN(31, 2, BlockCategory.PLANT),
    DEAD_BUSH(31, 2, BlockCategory.PLANT),
    PISTON(33, 0, BlockCategory.MISCELLANEOUS),
    WHITE_WOOL(35, 0, BlockCategory.CONSTRUCT),
    ORANGE_WOOL(35, 1, BlockCategory.CONSTRUCT),
    MAGENTA_WOOL(35, 2, BlockCategory.CONSTRUCT),
    LIGHT_BLUE_WOOL(35, 3, BlockCategory.CONSTRUCT),
    YELLOW_WOOL(35, 4, BlockCategory.CONSTRUCT),
    LIME_WOOL(35, 5, BlockCategory.CONSTRUCT),
    PINK_WOOL(35, 6, BlockCategory.CONSTRUCT),
    GRAY_WOOL(35, 7, BlockCategory.CONSTRUCT),
    LIGT_GRAY_WOOL(35, 7, BlockCategory.CONSTRUCT),
    CYAN_GRAY_WOOL(35, 8, BlockCategory.CONSTRUCT),
    PURPLE_WOOL(35, 9, BlockCategory.CONSTRUCT),
    BLUE_WOOL(35, 10, BlockCategory.CONSTRUCT),
    BROWN_WOOL(35, 11, BlockCategory.CONSTRUCT),
    GREEN_WOOL(35, 13, BlockCategory.CONSTRUCT),
    RED_WOOL(35, 14, BlockCategory.CONSTRUCT),
    BLACK_WOOL(35, 15, BlockCategory.CONSTRUCT),
    DANDELION(37, 0, BlockCategory.PLANT),
    POPPY(38, 0, BlockCategory.PLANT),
    BLUE_ORCHID(38, 1, BlockCategory.PLANT),
    ALLIUM(38, 2, BlockCategory.PLANT),
    AZURE_BLUET(38, 3, BlockCategory.PLANT),
    RED_TULIP(38, 4, BlockCategory.PLANT),
    ORANGE_TULIP(38, 5, BlockCategory.PLANT),
    WHITE_TULIP(38, 6, BlockCategory.PLANT),
    PINK_TULIP(38, 7, BlockCategory.PLANT),
    OXEYE_DAISY(38, 8, BlockCategory.PLANT),
    BROWN_MUSHROOM(39, 0, BlockCategory.PLANT),
    RED_MUSHROOM(40, 0, BlockCategory.PLANT),
    GOLD_BLOCK(41, 0, BlockCategory.PLANT),
    IRON_BLOCK(42, 0, BlockCategory.PLANT),
    DOUBLE_STONE_SLAB(43, 0, BlockCategory.CONSTRUCT),
    DOUBLE_STANDSTONE_SLAB(43, 1, BlockCategory.CONSTRUCT),
    DOUBLE_WOODEN_SLAB(43, 2, BlockCategory.CONSTRUCT),
    DOUBLE_COBBLESTONE_SLAB(43, 3, BlockCategory.CONSTRUCT),
    DOUBLE_BRICK_SLAB(43, 4, BlockCategory.CONSTRUCT),
    DOUBLE_STONE_BRICK_SLAB(43, 5, BlockCategory.CONSTRUCT),
    DOUBLE_NETHER_BRICK_SLAB(43, 6, BlockCategory.CONSTRUCT),
    DOUBLE_QUARTZ_SLAB(43, 7, BlockCategory.CONSTRUCT),
    STONE_SLAB(44, 0, BlockCategory.SLAB),
    SANDSTONE_SLAB(44, 1, BlockCategory.SLAB),
    WOODEN_SLAB(44, 2, BlockCategory.SLAB),
    COBBLESTONE_SLAB(44, 3, BlockCategory.SLAB),
    BRICK_SLAB(44, 4, BlockCategory.SLAB),
    STONE_BRICK_SLAB(44, 5, BlockCategory.SLAB),
    NETHER_BRICK_SLAB(44, 6, BlockCategory.SLAB),
    QUARTZ_SLAB(44, 7, BlockCategory.SLAB),
    BRICKS(45, 0, BlockCategory.CONSTRUCT),
    TNT(46, 0, BlockCategory.CONSTRUCT),
    BOOKSHELF(47, 0, BlockCategory.CONSTRUCT),
    MOSS_STONE(48, 0, BlockCategory.CONSTRUCT),
    OBSIDIAN(49, 0, BlockCategory.CONSTRUCT),
    //TORCH(50,0,)
    MONSTER_SPAWNER(52, 0, BlockCategory.CONSTRUCT),
    OAK_WOOD_STAIRS(53, 0, BlockCategory.CONSTRUCT),
    DIAMOND_ORE(56, 0, BlockCategory.CONSTRUCT),
    DIAMOND_BLOCK(57, 0, BlockCategory.CONSTRUCT),
    CRAFTING_TABLE(58, 0, BlockCategory.CONSTRUCT),
    WHEAT_CROPS(59, 0, BlockCategory.CONSTRUCT),
    FARMLAND(60, 0, BlockCategory.CONSTRUCT),
    FURNACE(61, 0, BlockCategory.MISCELLANEOUS),
    BURNING_FURNACE(62, 0, BlockCategory.MISCELLANEOUS),
    OAK_DOOR_BLOCK(64, 0, BlockCategory.DOOR),
    RAIL(66, 0, BlockCategory.CONSTRUCT),
    COBBELSTONE_STAIRS(67, 0, BlockCategory.STAIRS),
    STONE_PRESSURE_PLATE(70, 0, BlockCategory.PLATE),
    IRON_DOOR_BLOCK(71, 0, BlockCategory.DOOR),
    WOODEN_PRESSURE_PLATE(72, 0, BlockCategory.PLATE),
    REDSTONE_ORE(73, 0, BlockCategory.CONSTRUCT),
    GLOWING_REDSTONE_ORE(74, 0, BlockCategory.CONSTRUCT),
    STONE_BUTTON(77, 0, BlockCategory.MISCELLANEOUS),
    SNOW(78, 0, BlockCategory.CONSTRUCT),
    ICE(79, 0, BlockCategory.CONSTRUCT),
    SNOW_BLOCK(80, 0, BlockCategory.CONSTRUCT),
    CACTUS(81, 0, BlockCategory.CONSTRUCT),
    CLAY(82, 0, BlockCategory.CONSTRUCT),
    SUGAR_CANNES(83, 0, BlockCategory.PLANT),
    JUKEBOX(84, 0, BlockCategory.CONSTRUCT),
    OAK_FENCE(85, 0, BlockCategory.CONSTRUCT),
    PUMPKIN(86, 0, BlockCategory.MISCELLANEOUS),
    NETHERRACK(87, 0, BlockCategory.CONSTRUCT),
    SOUL_SAND(88, 0, BlockCategory.CONSTRUCT),
    GLOWSTONE(89, 0, BlockCategory.CONSTRUCT),
    NETHER_PORTAL(90, 0, BlockCategory.CONSTRUCT),
    JACK_O_LANTERN(91, 0, BlockCategory.MISCELLANEOUS),
    CAKE_BLOCK(92, 0, BlockCategory.MISCELLANEOUS),
    WHITE_STAINED_GLASS(95, 0, BlockCategory.CONSTRUCT),
    ORANGE_STAINED_GLASS(95, 1, BlockCategory.CONSTRUCT),
    MAGENTA_STAINED_GLASS(95, 2, BlockCategory.CONSTRUCT),
    LIGHT_BLUE_STAINED_GLASS(95, 3, BlockCategory.CONSTRUCT),
    YELLOW_STAINED_GLASS(95, 4, BlockCategory.CONSTRUCT),
    LIME_STAINED_GLASS(95, 5, BlockCategory.CONSTRUCT),
    PINK_STAINED_GLASS(95, 6, BlockCategory.CONSTRUCT),
    GRAY_STAINED_GLASS(95, 7, BlockCategory.CONSTRUCT),
    LIGHT_GRAY_STAINED_GLASS(95, 8, BlockCategory.CONSTRUCT),
    CYAN_STAINED_GLASS(95, 9, BlockCategory.CONSTRUCT),
    PURPLE_STAINED_GLASS(95, 10, BlockCategory.CONSTRUCT),
    BLUE_STAINED_GLASS(95, 11, BlockCategory.CONSTRUCT),
    BROWN_STAINED_GLASS(95, 12, BlockCategory.CONSTRUCT),
    GREEN_STAINED_GLASS(95, 13, BlockCategory.CONSTRUCT),
    RED_STAINED_GLASS(95, 14, BlockCategory.CONSTRUCT),
    BLACK_STAINED_GLASS(95, 15, BlockCategory.CONSTRUCT),
    //WOODEN_TRAPDOOR(96,0,),
    STONE_MONSTER_EGG(97, 0, BlockCategory.CONSTRUCT),
    COBBELSTONE_MONSTER_EGG(97, 1, BlockCategory.CONSTRUCT),
    STONE_BRICK_MONSTER_EGG(97, 2, BlockCategory.CONSTRUCT),
    MOSSY_STONE_BRICK_MONSTER_EGG(97, 3, BlockCategory.CONSTRUCT),
    CRACKED_STONE_BRICK_MONSTER_EGG(97, 4, BlockCategory.CONSTRUCT),
    CHISELED_STONE_BRICK_MONSTER_EGG(97, 5, BlockCategory.CONSTRUCT),
    STONE_BRICK(98, 0, BlockCategory.CONSTRUCT),
    MOSSY_STONE_BRICK(98, 1, BlockCategory.CONSTRUCT),
    CRACKED_STONE_BRICK(98, 2, BlockCategory.CONSTRUCT),
    CHISELED_STONE_BRICK(98, 3, BlockCategory.CONSTRUCT),
    BROWN_MUSHROOM_BLOCK(99, 0, BlockCategory.CONSTRUCT),
    RED_MUSHROOM_BLOCK(100, 0, BlockCategory.CONSTRUCT),
    IRON_BARS(101, 0, BlockCategory.CONSTRUCT),
    GLASS_PANE(102, 0, BlockCategory.CONSTRUCT),
    MELON_BLOCK(103, 0, BlockCategory.CONSTRUCT),
    PUMPKIN_STEM(104, 0, BlockCategory.PLANT),
    MELON_STEM(105, 0, BlockCategory.PLANT),
    OAK_FENCE_GATE(107, 0, BlockCategory.CONSTRUCT),
    BRICK_STAIRS(108, 0, BlockCategory.STAIRS),
    STONE_BRICK_STAIRS(109, 0, BlockCategory.STAIRS),
    MYCELIUM(110, 0, BlockCategory.CONSTRUCT),
    LILY_PAD(111, 0, BlockCategory.PLANT),
    NETHER_BRICK(112, 0, BlockCategory.CONSTRUCT),
    NETHER_BRICK_FENCE(113, 0, BlockCategory.CONSTRUCT),
    NETHER_BRICK_STAIRS(114, 0, BlockCategory.STAIRS),
    NETHER_WART(115, 0, BlockCategory.PLANT),
    ENCHANTEMENT_TABLE(116, 0, BlockCategory.CONSTRUCT),
    BREWING_STAND(117, 0, BlockCategory.CONSTRUCT),
    CAULDRON(118, 0, BlockCategory.CONSTRUCT),
    END_PORTAL(119, 0, BlockCategory.MISCELLANEOUS),
    END_PORTAL_FRAME(120, 0, BlockCategory.CONSTRUCT),
    END_STONE(121, 0, BlockCategory.CONSTRUCT),
    DRAGON_EGG(122, 0, BlockCategory.CONSTRUCT),
    REDSTONE_LAMP_INACTIVE(123, 0, BlockCategory.CONSTRUCT),
    REDSTONE_LAMP_ACTIVE(124, 0, BlockCategory.CONSTRUCT),
    DOUBLE_OAK_WOOD_SLAB(125, 0, BlockCategory.CONSTRUCT),
    DOUBLE_SPRUCE_WOOD_SLAB(125, 1, BlockCategory.CONSTRUCT),
    DOUBLE_BIRCH_WOOD_SLAB(125, 2, BlockCategory.CONSTRUCT),
    DOUBLE_JUNGLE_WOOD_SLAB(125, 4, BlockCategory.CONSTRUCT),
    DOUBLE_ACACIA_WOOD_SLAB(125, 4, BlockCategory.CONSTRUCT),
    DOUBLE_DARK_OAK_WOOD_SLAB(125, 5, BlockCategory.CONSTRUCT),
    OAK_WOOD_SLAB(126, 0, BlockCategory.SLAB),
    SPRUCE_WOOD_SLAB(126, 1, BlockCategory.SLAB),
    BIRCH_WOOD_SLAB(126, 2, BlockCategory.SLAB),
    JUNGLE_WOOD_SLAB(126, 3, BlockCategory.SLAB),
    ACACIA_WOOD_SLAB(126, 4, BlockCategory.SLAB),
    DARK_OAK_WOOD_SLAB(126, 5, BlockCategory.SLAB),
    COCOA(127, 0, BlockCategory.PLANT),
    SANDSTONE_STAIRS(128, 0, BlockCategory.STAIRS),
    EMERALD_ORE(129, 0, BlockCategory.CONSTRUCT),
    EMERALD_BLOCK(133, 0, BlockCategory.CONSTRUCT),
    SPRUCE_WOOD_STAIRS(134, 0, BlockCategory.STAIRS),
    BIRCH_WOOD_STAIRS(135, 0, BlockCategory.STAIRS),
    JUNGLE_WOOD_STAIRS(136, 0, BlockCategory.STAIRS),
    COMMAND_BLOCK(137, 0, BlockCategory.CONSTRUCT),
    BEACON(138, 0, BlockCategory.CONSTRUCT),
    COBBELSTONE_WALL(139, 0, BlockCategory.CONSTRUCT),
    MOSSY_COBBLESTONE_WALL(139, 1, BlockCategory.CONSTRUCT),
    FLOWER_POT(140, 0, BlockCategory.CONSTRUCT), // TODO Correct ?
    CARROTS(141, 0, BlockCategory.PLANT),
    POTATOES(142, 0, BlockCategory.PLANT),
    WOODEN_BUTTON(143, 0, BlockCategory.MISCELLANEOUS),
    MOB_HEAD(144, 0, BlockCategory.MISCELLANEOUS),
    ANVIL(145, 0, BlockCategory.CONSTRUCT),
    GOLD_PLATE(147, 0, BlockCategory.PLATE),
    IRON_PLATE(148, 0, BlockCategory.PLATE),
    REDSTONE_COMPARATOR_INACTIVE(149, 0, BlockCategory.PLATE),
    REDSTONE_COMPARATOR_ACTIVE(150, 0, BlockCategory.PLATE),
    DAYLIGHTSENSOR(151, 0, BlockCategory.CONSTRUCT),
    REDSTONE_BLOCK(152, 0, BlockCategory.CONSTRUCT),
    NETHER_QUARTZ_ORE(153, 0, BlockCategory.CONSTRUCT),
    HOPPER(154, 0, BlockCategory.CONSTRUCT),
    QUARTZ_BLOCK(155, 0, BlockCategory.CONSTRUCT),
    CHISELED_QUARTZ_BLOCK(155, 1, BlockCategory.CONSTRUCT),
    PILLAR_QUARTZ_BLOCK(155, 2, BlockCategory.CONSTRUCT),
    QUARTZ_STAIRS(156, 0, BlockCategory.STAIRS),
    DROPPER(158, 0, BlockCategory.MISCELLANEOUS),
    WHITE_HARDENED_CLAY(159, 0, BlockCategory.CONSTRUCT),
    ORANGE_HARDENED_CLAY(159, 1, BlockCategory.CONSTRUCT),
    MAGENTA_HARDENED_CLAY(159, 2, BlockCategory.CONSTRUCT),
    LIGHT_BLUE_HARDNED_CLAY(159, 3, BlockCategory.CONSTRUCT),
    YELLOW_HARDNED_CLAY(159, 4, BlockCategory.CONSTRUCT),
    LIME_HARDNED_CLAY(159, 5, BlockCategory.CONSTRUCT),
    PINK_HARDNED_CLAY(159, 6, BlockCategory.CONSTRUCT),
    GRAY_HARDNED_CLAY(159, 7, BlockCategory.CONSTRUCT),
    LIGHT_GRAY_HARDNED_CLAY(159, 8, BlockCategory.CONSTRUCT),
    CYAN_HARDNED_CLAY(159, 9, BlockCategory.CONSTRUCT),
    PURPLE_HARDENED_CLAY(159, 10, BlockCategory.CONSTRUCT),
    BLUE_HARDNED_CLAY(159, 11, BlockCategory.CONSTRUCT),
    BROWN_HARDNED_CLAY(159, 12, BlockCategory.CONSTRUCT),
    GREEN_HARDNED_CLAY(159, 13, BlockCategory.CONSTRUCT),
    RED_HARDNED_CLAY(159, 14, BlockCategory.CONSTRUCT),
    BLACK_HARDNED_CLAY(159, 15, BlockCategory.CONSTRUCT);

    @Getter
    public int id, shortId;
    @Getter
    public BlockCategory blockCategory;

    BlockData(int id, int shortId, BlockCategory blockCategory) {
        this.id = id;
        this.shortId = shortId;
        this.blockCategory = blockCategory;
    }

    public static BlockData getBlockDataById(int id) {
        return Arrays.stream(BlockData.values())
                .filter(blockData -> Objects.equals(blockData.getId(),id))
                .findFirst()
                .get();
    }

    /***
     * Retourne une liste des blocs dans une catégorie précisé
     *
     * @param category
     * @return
     */
    public static List<BlockData> blockDataCategory(BlockCategory category) {
       return Stream.of(BlockData.values())
                .filter(blockData -> blockData.blockCategory.equals(category))
                .collect(Collectors.toList());
    }


    public enum BlockCategory {
        CONSTRUCT,
        SAPLING,
        PLANT,
        SLAB,
        DOOR,
        PLATE,
        // Spécial - Direction par rapport à l'endroit posé
        STAIRS,
        LOG,
        // Spécial - Direction par rapport aux regards
        MISCELLANEOUS
    }

    @Data(staticConstructor = "of")
    public static class Pair<BlockDataA, BlockDataB> {
        public final BlockDataA left;
        public final BlockDataB right;
}
}
